data:extend({
    {
        type = "item",
        name = "pda-road-sign-speed-limit",
        icon = "__PavementDriveAssistContinued__/graphics/icons/icon_speed_limit.png",
        icon_size = 32,
        flags = {},
        subgroup = "circuit-network",
        place_result="pda-road-sign-speed-limit",
        order = "d[other]-c[programmable-speaker]",
        stack_size= 50,
    },
    {
        type = "item",
        name = "pda-road-sign-speed-unlimit",
        icon = "__PavementDriveAssistContinued__/graphics/icons/icon_speed_unlimit.png",
        icon_size = 32,
        flags = {},
        subgroup = "circuit-network",
        place_result="pda-road-sign-speed-unlimit",
        order = "d[other]-d[pda-road-sign-speed-limit]",
        stack_size= 50,
    },
    {
        type = "item",
        name = "pda-road-sign-stop",
        icon = "__PavementDriveAssistContinued__/graphics/icons/stop-sign.png",
        icon_size = 64, icon_mipmaps = 4,
        flags = {},
        subgroup = "circuit-network",
        place_result="pda-road-sign-stop",
        order = "d[other]-f[pda-road-sign-stop]",
        stack_size= 50,
    },
    {
        type = "item",
        name = "pda-road-sensor",
        icon = "__PavementDriveAssistContinued__/graphics/icons/road-sensor.png",
        icon_size = 64, icon_mipmaps = 4,
        flags = {},
        subgroup = "circuit-network",
        place_result="pda-road-sensor",
        order = "d[other]-e[pda-road-sensor]",
        stack_size= 50,
    },
})
