data:extend({
        {
            type = "shortcut",
            name = "pda-cruise-control-toggle",
            associated_control_input = "toggle_cruise_control",
            order = "a",
            action = "lua",
            localised_name = {"controls.toggle_cruise_control"},
            toggleable = true,
            icon = "__PavementDriveAssistContinued__/graphics/shortcuts/cc-32px.png",
            icon_size = 32,
            small_icon = "__PavementDriveAssistContinued__/graphics/shortcuts/cc-24px.png",
            small_icon_size = 24,
        },
        {
            type = "shortcut",
            name = "pda-set-cruise-control-limit",
            associated_control_input = "set_cruise_control_limit",
            order = "a",
            action = "lua",
            localised_name = {"controls.set_cruise_control_limit"},
            style = "green",
            icon = "__PavementDriveAssistContinued__/graphics/shortcuts/set-cc-32px-white.png",
            icon_size = 32,
            small_icon = "__PavementDriveAssistContinued__/graphics/shortcuts/cc-24px.png",
            small_icon_size = 24,
        },
        {
            type = "shortcut",
            name = "pda-drive-assistant-toggle",
            associated_control_input = "toggle_drive_assistant",
            order = "a",
            action = "lua",
            localised_name = {"controls.toggle_drive_assistant"},
            toggleable = true,
            icon = "__PavementDriveAssistContinued__/graphics/shortcuts/pda-32px.png",
            icon_size = 32,
            small_icon = "__PavementDriveAssistContinued__/graphics/shortcuts/pda-24px.png",
            small_icon_size = 24,
        },
})
